/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package advent

import java.io.File
import kotlin.collections.mutableListOf

class Rps {
    fun getLines(file: String): List<String> {
        return File(file).useLines { it.toList() }
    }

    fun getPoints(lines: List<String>): List<Int?> {
        val points = mutableListOf<Int?>()
        lines.forEach { line ->
                points.add(strategyMap[line])
        }
        return points
    }

    val outcomeMap =
            mapOf(
                    "A X" to 4,
                    "A Y" to 8,
                    "A Z" to 3,
                    "B X" to 1,
                    "B Y" to 5,
                    "B Z" to 9,
                    "C X" to 7,
                    "C Y" to 2,
                    "C Z" to 6
            )
    val strategyMap =
            mapOf(
                    "A X" to 3,
                    "A Y" to 4,
                    "A Z" to 8,
                    "B X" to 1,
                    "B Y" to 5,
                    "B Z" to 9,
                    "C X" to 2,
                    "C Y" to 6,
                    "C Z" to 7
            )
}
    val strategyMap =
            mapOf(
                    "A X" to 3,
                    "A Y" to 4,
                    "A Z" to 8,
                    "B X" to 1,
                    "B Y" to 5,
                    "B Z" to 9,
                    "C X" to 2,
                    "C Y" to 6,
                    "C Z" to 7
            )

fun main() {
    val file = "/home/sean/src/kotlin/advent/day2/input.txt"
    val rps = Rps()
    val lines = rps.getLines(file)
    val points = rps.getPoints(lines)
    println("Points: " + points.filterNotNull().sum())
}
