/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package advent

import java.io.File
import kotlin.collections.mutableListOf

class Stacker() {

    var stack = initStack()

    fun getLines(file: String): List<String> {
        return File(file).useLines { it.toList() }
    }

    fun parsePositions(lines: List<String>) {
        lines.forEach { x -> run {
            x.forEachIndexed { k,v -> run {
                if (k % 4 == 1 && !v.isWhitespace() && !v.isDigit()) {
                    var index = (k-1)/4
                    stack[index].addLast(v)
                }
            }}
        }}
    }

    fun parseMoves(lines: List<String>) {
        lines.forEach { x -> run {
            var removedMove = x.split("move ")[1]
            var (boxes, toFrom) = removedMove.split(" from ")
            var (from, to) = toFrom.split(" to ")
            //println("move $boxes from $from to $to")

            // range of boxes boxes = 1..boxes
            // pop from, push to
            var temp = ArrayDeque<Char>()
            for(box in 1..boxes.toInt()) {
                var fromIndex = from.toInt()-1
                if (stack[fromIndex].size > 0) {
                    var c = stack[fromIndex].removeFirst()
                    temp.addFirst(c)
                    //stack[toIndex].addFirst(c)
                }
            }
            for(box in 1..boxes.toInt()) {
                var toIndex = to.toInt()-1
                var c = temp.removeFirst()
                stack[toIndex].addFirst(c)
            }
        }}
    }

    fun getTopOfEach() {
        stack.forEachIndexed { k, v -> run {
            if(v.size > 0){
                var first = v.first()
                println("Top: $k: $first")
            }
        }}
    }

    fun initStack(): List<ArrayDeque<Char>> {
        var list = mutableListOf(ArrayDeque<Char>())
        for(i in 1..8) {
            list.add(ArrayDeque<Char>())
        }
        return list
    }

}

fun main() {
    val filePos = "/home/sean/src/kotlin/advent/day5/input-positions.txt"
    val fileMoves = "/home/sean/src/kotlin/advent/day5/input-moves.txt"
    val stacker = Stacker()
    val posLines = stacker.getLines(filePos)
    val moveLines = stacker.getLines(fileMoves)

    stacker.parsePositions(posLines)
    stacker.parseMoves(moveLines)
    stacker.getTopOfEach()

}
