/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package advent

import kotlin.collections.mutableListOf
import java.io.File

fun main() {
    println(getCaloriesPerElf(getLines("/home/sean/src/kotlin/advent/day1.txt")).sortedDescending().take(3).sum())
}

fun getLines(file: String): List<String> {
    return File(file).useLines { it.toList() }
}

fun getCaloriesPerElf(lines: List<String>): List<Int> {
    var elves = mutableListOf<Int>()
    var calories = 0
    lines.forEach {
        line -> run {
            if(line.isNullOrEmpty()) {
                elves.add(calories)
                calories = 0
                return@forEach
            }
            calories += line.toInt()
        }
    }
    return elves.toList()
}
